pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing Completed..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deployment completed....'
            }
        }
        stage('Hello') {
            steps {
                echo 'Hello World'
            }            
        }
    }
}
